version: "3"
services:
  proxy:
    image: vpnproxy
    environment: 
      - PORT=8888
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:8888
    # https://stackoverflow.com/questions/30547484/calling-openconnect-vpn-client-in-docker-container-shows-tunsetiff-failed-opera
    cap_add: 
      - NET_ADMIN
    command: bash -c '
        tinyproxy &&
        ${CMD}
      '